import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Translator App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
          rel="stylesheet"
        />
      </Head>
      <main className="w-screen h-screen flex flex-col justify-center items-center">
        <h1 className="bg-red-300">Hello let's build translator app</h1>
        <form className="pt-4">
          <input type="text" className="border-2 border-indigo-300" />
          <button
            type="submit"
            className="bg-indigo-300 px-4 py-1 ml-4 rounded-full"
          >
            Send Message
          </button>
        </form>
      </main>
    </>
  );
}
